apiVersion: v1
kind: Service
metadata:
  name: smurl-web
spec:
  type: LoadBalancer
  selector:
    app: smurl-web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smurl-api
spec:
  type: LoadBalancer
  selector:
    app: smurl-api
  ports:
    targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smurl-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smurl-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smurl-web
    spec:
      containers:
      - name: smurl-web
        image: chrwalte/smurl_web:1.0.33
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smurl-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smurl-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smurl-api
    spec:
      containers:
      - name: smurl-api
        image: chrwalte/smurl_api:1.0.30
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: 6je6juNbNWsdNG2WNY6PdGSdUTBd5JfW
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume